spring:
  application:
    name: nut-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: your-api-key
      chat:
        options:
          model: qwen-plus
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xqj.nutaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: your-api-key
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG