spring:
  application:
    name: nut-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: your-api-key
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xqj.nutaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: 114514